### ISSUE TITLE
any update?

### ISSUE THREAD

**Issue by zhangguanghui1** [zhenheny/LEGO#1]
Hope you release your code!Thanks a lot!

**Comment by zhenheny** [comment]
Just back from conference. Will do during this week. Please stay tuned.

**Comment by zhangguanghui1** [comment]
Okay, Thank you for your reply! good luck!

**Comment by zhenheny** [comment]
Hi, I just uploaded the files I have. Please refer to data folder for data preparation and run_train.sh for training. I will update documentation and trained model later.

**Comment by zhangguanghui1** [comment]
@zhenheny Thank you so much!
